# Dockerfile for Playwright tests

# Base image for Playwright tests
FROM mcr.microsoft.com/playwright:v1.37.0-focal AS playwright

# Set working directory for tests
WORKDIR /app/test

# Copy test files
COPY test/package.json test/package-lock.json ./
RUN npm install
RUN npx playwright install
COPY test/ ./
RUN npx bddgen

# Start Playwright tests
CMD ["npx", "playwright", "test"]
# CMD ["sh", "-c", "cd /app/test && npx bddgen && npx playwright test"]