# syntax=docker/dockerfile:1.7-labs

# Dockerfile for backend

# Base image for backend
FROM node:slim AS backend

# Set working directory for backend
WORKDIR /app/server

# Copy backend files
COPY /server/package.json /server/package-lock.json ./
RUN npm install
COPY --exclude=/server/node_modules/**/*.* /server/ ./

# Expose port
EXPOSE 5000

# Start both backend
# CMD ["node", "index.js"]
# CMD ["sh", "-c", "cd /app/server && node index.js"]
