# Dockerfile for frontend

# Base image for frontend
FROM node:slim AS frontend

# Set working directory for frontend
WORKDIR /app/client

# Copy frontend files
COPY client/package.json client/package-lock.json ./
RUN npm install
COPY client/ ./

# Expose ports
EXPOSE 3000

# Start both frontend
CMD ["npm", "start"]
# CMD ["sh", "-c", "cd /app/client && npm start"]