version: '3.8'
services:
  client:
    build: ./client/greenacre-loans
    ports:
      - "3000:3000"
    environment:
      - BACKEND_PORT=8080
      - BACKEND_HOST=server
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - URL=http://server
